### ISSUE TITLE
User stories tracker 

### ISSUE THREAD

**Issue by hmintoh** [hmintoh/eventix-asia#9]
## As an admin I should be able to: 
- [ ] Login securely
- [ ] Access the admin portal 
- [ ] Re-visit the admin portal
- [ ] Edit a listing
- [ ] Approve a listing
- [ ] Reject a listing 
- [ ] See high level summary to events and users 

### Website
- [x] Access the checkout page
- [ ] Choose desired event, date and ticket quantity
- [ ] Review details before confirmation
- [ ] Submit request
- [ ] Receive confirmation that request has been successfully received
- [ ] GTH: subscriptions

### Dashboard
- [ ] Login securely
- [ ] Access my own dashboard only
- [ ] Re-visit my dashboard
- [ ] See past and upcoming events I have registered for
- [ ] GTH: write reviews for past events

## As a vendor I should be able to:
- [ ] Login securely
- [ ] Access my own dashboard only
